sudo: false

language: go

go:
  - 1.14.x
  - 1.15.x
  - 1.16.x
  - 1.17.x

env:
  - GO111MODULE=on

# Get deps, build, test, and ensure the code is gofmt'ed.
script:
  - go test -v ./...
  - diff -u <(echo -n) <(gofmt -d -s .)
